Meteor 3.0 compatibility
Meteor-Community-Packages/meteor-collection-extensions pull request #26
Opened 2023-12-21 09:52 UTC by jankapunkt

This is the base branch to make this package Meteor 3.0 compatible

2024-01-04 22:48 UTC, harryadel approved these changes
Great work, I expected that you'd drop some packages from tests which is what happened. The testing of these package is really weird and annoying since it relies on sibling packages to see if the library works with them.

2024-01-05 09:32 UTC, jankapunkt commented
I only dropped `ongoworks:secrutiy` and `lai:document-methods` as they are out of reach for us. However, I contacted the owners for transfer so we can soon include them back,

2024-01-09 18:17 UTC, StorytellerCZ approved these changes

2024-01-15 13:20 UTC, harryadel commented
Thanks @jankapunkt

2024-04-15 10:55 UTC, jankapunkt commented
Published `1.0.0-beta300.2`

2024-04-15 10:56 UTC, jankapunkt commented
@StorytellerCZ @harryadel tests are fixed and run for 3.x AND 2.x

2024-04-15 12:29 UTC, StorytellerCZ requested changes

2024-04-15 12:29 UTC, StorytellerCZ commented on package.js
> +  api.versionsFrom(['2.8.0', '3.0-beta.0'])
Here it should be at least `3.0-beta.7`

2024-04-16 05:31 UTC, jankapunkt commented
@harryadel @StorytellerCZ I fixed all tests that crashed due to dependency issues and released `1.0.0-beta300.2` for testing. You can use it in your apps and it should work out well with latest collection2, too!

2024-04-22 13:36 UTC, harryadel reviewed
I'm not going to block this PR but please give a careful thought to my comments, thank you :)

2024-04-22 13:36 UTC, harryadel commented on .github/workflows/testsuite.yml
> +          - '3.0-beta.0'
It's best to use the latest RC instead of the beta. This goes for all places that a meteor version is used.

2024-04-22 13:36 UTC, harryadel commented on CHANGELOG.md
> +- BREAKING!
Looks beautiful, thank you <3

2024-04-22 13:36 UTC, harryadel commented on .versions
> +aldeed:collection2@4.0.0-beta.7
The latest collection2 version is [about to be](https://github.com/Meteor-Community-Packages/meteor-collection2/pull/449) 4.0.2 ;)

2024-04-22 13:36 UTC, harryadel commented on tests/tests.coffee
> +{ CollectionExtensions } = require('meteor/lai:collection-extensions')
Would be possible to rework this coffee script file into vanilla JS? This goes well with the spirit of a new breaking versions.

2024-06-11 09:40 UTC, jankapunkt commented
published `1.0.0-rc300.0` → 3.0-rc.2 compatibility

2024-07-16 09:12 UTC, StorytellerCZ commented
I think just some of the dependencies here need to get final version and then we are ready to go here.

2025-10-20 15:01 UTC, merged